# Generated by Django 4.2.30 on 2026-07-04 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='元数据名称')),
                ('field_type', models.CharField(choices=[('string', '字符串'), ('integer', '整数'), ('decimal', '小数'), ('date', '日期'), ('datetime', '日期时间'), ('boolean', '布尔值'), ('text', '文本')], max_length=20, verbose_name='字段类型')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='长度')),
                ('decimal_places', models.IntegerField(blank=True, null=True, verbose_name='小数位数')),
                ('control_type', models.CharField(choices=[('input', '输入框'), ('select', '下拉框'), ('radio', '单选框'), ('checkbox', '多选框'), ('datepicker', '日期选择器'), ('textarea', '文本域')], max_length=20, verbose_name='前端控件类型')),
                ('storage_type', models.CharField(choices=[('code_only', '仅存储CODE'), ('code_name', '独立存储CODE和NAME')], default='code_only', max_length=20, verbose_name='存储方式')),
                ('default_value', models.CharField(blank=True, max_length=200, null=True, verbose_name='默认值')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('validation_rule', models.CharField(blank=True, max_length=500, null=True, verbose_name='校验规则')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '元数据配置',
                'verbose_name_plural': '元数据配置',
            },
        ),
        migrations.CreateModel(
            name='ParameterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='参数表名称')),
                ('business_description', models.TextField(verbose_name='业务说明')),
                ('domain', models.CharField(max_length=100, verbose_name='所属业务领域')),
                ('owner', models.CharField(max_length=100, verbose_name='负责人')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('deprecated', '废弃')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('version', models.IntegerField(default=1, verbose_name='版本')),
            ],
            options={
                'verbose_name': '参数表业务说明底账',
                'verbose_name_plural': '参数表业务说明底账',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_no', models.CharField(max_length=50, unique=True, verbose_name='需求编号')),
                ('title', models.CharField(max_length=200, verbose_name='需求标题')),
                ('requirement_type', models.CharField(choices=[('new', '新增'), ('modify', '变更'), ('reuse', '复用')], max_length=20, verbose_name='需求类型')),
                ('business_description', models.TextField(verbose_name='业务说明')),
                ('requester', models.CharField(max_length=100, verbose_name='申请人')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='申请日期')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已审核'), ('in_progress', '进行中'), ('completed', '已完成'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('story_points', models.IntegerField(blank=True, null=True, verbose_name='故事点')),
                ('sprint', models.CharField(blank=True, max_length=50, null=True, verbose_name='冲刺')),
                ('project_platform_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目管理平台ID')),
                ('parameter_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameter.parametertable', verbose_name='关联参数表')),
            ],
            options={
                'verbose_name': '业务需求登记',
                'verbose_name_plural': '业务需求登记',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=50, verbose_name='用例编号')),
                ('title', models.CharField(max_length=200, verbose_name='用例标题')),
                ('case_type', models.CharField(choices=[('normal', '正常流程'), ('boundary', '边界条件'), ('exception', '异常场景')], max_length=20, verbose_name='用例类型')),
                ('preconditions', models.TextField(blank=True, null=True, verbose_name='前置条件')),
                ('steps', models.TextField(verbose_name='测试步骤')),
                ('expected_result', models.TextField(verbose_name='预期结果')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('reviewed', '已评审'), ('automated', '已自动化'), ('executed', '已执行')], default='draft', max_length=20, verbose_name='状态')),
                ('automated', models.BooleanField(default=False, verbose_name='是否自动化')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='parameter.requirement', verbose_name='关联需求')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
            },
        ),
        migrations.CreateModel(
            name='TaskDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_no', models.CharField(max_length=50, verbose_name='任务书编号')),
                ('title', models.CharField(max_length=200, verbose_name='任务书标题')),
                ('document_type', models.CharField(choices=[('word', 'Word'), ('pdf', 'PDF')], max_length=20, verbose_name='文档类型')),
                ('content', models.TextField(verbose_name='任务书内容')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('exported_at', models.DateTimeField(blank=True, null=True, verbose_name='导出时间')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_documents', to='parameter.requirement', verbose_name='关联需求')),
            ],
            options={
                'verbose_name': '任务书管理',
                'verbose_name_plural': '任务书管理',
            },
        ),
        migrations.CreateModel(
            name='IndexIdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_id', models.CharField(max_length=50, unique=True, verbose_name='INDEXID')),
                ('business_name', models.CharField(max_length=200, verbose_name='业务名称')),
                ('business_description', models.TextField(blank=True, null=True, verbose_name='业务说明')),
                ('custom_column_names', models.JSONField(blank=True, null=True, verbose_name='自定义列名配置')),
                ('display_fields', models.JSONField(blank=True, null=True, verbose_name='显示字段配置')),
                ('validation_rules', models.JSONField(blank=True, null=True, verbose_name='校验规则配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parameter_table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parameter.parametertable', verbose_name='关联参数表')),
            ],
            options={
                'verbose_name': 'INDEXID配置',
                'verbose_name_plural': 'INDEXID配置',
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='字段名')),
                ('display_name', models.CharField(max_length=200, verbose_name='显示名称')),
                ('field_type', models.CharField(max_length=20, verbose_name='字段类型')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='长度')),
                ('decimal_places', models.IntegerField(blank=True, null=True, verbose_name='小数位数')),
                ('control_type', models.CharField(max_length=20, verbose_name='前端控件类型')),
                ('storage_type', models.CharField(max_length=20, verbose_name='存储方式')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('validation_rule', models.CharField(blank=True, max_length=500, null=True, verbose_name='校验规则')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序号')),
                ('is_custom', models.BooleanField(default=False, verbose_name='是否定制开发')),
                ('custom_requirement', models.TextField(blank=True, null=True, verbose_name='定制化需求')),
                ('metadata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameter.metadata', verbose_name='引用元数据')),
                ('parameter_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='parameter.parametertable', verbose_name='所属参数表')),
            ],
            options={
                'verbose_name': '字段定义',
                'verbose_name_plural': '字段定义',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ConfigScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_type', models.CharField(max_length=50, verbose_name='脚本类型')),
                ('script_content', models.TextField(verbose_name='脚本内容')),
                ('status', models.CharField(choices=[('generated', '已生成'), ('submitted', '已提交'), ('deployed', '已部署'), ('failed', '失败')], default='generated', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('deployed_at', models.DateTimeField(blank=True, null=True, verbose_name='部署时间')),
                ('environment', models.CharField(blank=True, max_length=50, null=True, verbose_name='目标环境')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_scripts', to='parameter.requirement', verbose_name='关联需求')),
            ],
            options={
                'verbose_name': '配置脚本',
                'verbose_name_plural': '配置脚本',
            },
        ),
        migrations.CreateModel(
            name='AutomationTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateTimeField(auto_now_add=True, verbose_name='执行日期')),
                ('status', models.CharField(choices=[('passed', '通过'), ('failed', '失败'), ('skipped', '跳过')], max_length=20, verbose_name='执行状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='执行时长(秒)')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='parameter.testcase', verbose_name='关联测试用例')),
            ],
            options={
                'verbose_name': '自动化测试结果',
                'verbose_name_plural': '自动化测试结果',
            },
        ),
    ]
