# Generated by Django 4.2.30 on 2026-07-04 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexidconfig',
            name='parameter_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter.parametertable', verbose_name='关联参数表'),
        ),
    ]
