# Generated by Django 4.2.30 on 2026-07-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0003_role_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='storage_type',
        ),
    ]
