# Generated by Django 4.2.30 on 2026-07-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0004_remove_metadata_storage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametertable',
            name='is_simple',
            field=models.BooleanField(default=False, verbose_name='是否SIMPLE表'),
        ),
    ]
