# Generated by Django 4.2.30 on 2026-07-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0005_parametertable_is_simple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexidconfig',
            name='parameter_table',
        ),
        migrations.AddField(
            model_name='metadata',
            name='field_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='字段名称英文'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='assignee',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='flow_comment',
            field=models.TextField(blank=True, null=True, verbose_name='流转备注'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='flow_status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('processed', '处理中'), ('done', '已完成')], default='draft', max_length=20, verbose_name='流转状态'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='flow_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='流转时间'),
        ),
    ]
