# Generated by Django 4.2.30 on 2026-07-08 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0006_remove_indexidconfig_parameter_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='字段名')),
                ('display_name', models.CharField(max_length=200, verbose_name='显示名称')),
                ('field_type', models.CharField(max_length=20, verbose_name='字段类型')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='长度')),
                ('decimal_places', models.IntegerField(blank=True, null=True, verbose_name='小数位数')),
                ('control_type', models.CharField(max_length=20, verbose_name='前端控件类型')),
                ('storage_type', models.CharField(max_length=20, verbose_name='存储方式')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('validation_rule', models.CharField(blank=True, max_length=500, null=True, verbose_name='校验规则')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序号')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='是否确认')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('field_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameter.fielddefinition', verbose_name='引用字段定义')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_configs', to='parameter.requirement', verbose_name='关联需求')),
            ],
            options={
                'verbose_name': '需求字段配置',
                'verbose_name_plural': '需求字段配置',
                'ordering': ['sort_order'],
            },
        ),
    ]
