# Generated by Django 4.2.30 on 2026-07-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0007_requirementfieldconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametertable',
            name='name_en',
            field=models.CharField(default='DEFAULT_TABLE', help_text='由大写字母和下划线组成，如：USER_INFO', max_length=200, verbose_name='英文名称（正式名称）'),
        ),
        migrations.AlterField(
            model_name='parametertable',
            name='name',
            field=models.CharField(help_text='用于解释说明', max_length=200, verbose_name='中文名称'),
        ),
    ]
