# Generated by Django 4.2.30 on 2026-07-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0008_parametertable_name_en_alter_parametertable_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexidconfig',
            options={'verbose_name': '成品表复用配置', 'verbose_name_plural': '成品表复用配置'},
        ),
        migrations.AddField(
            model_name='indexidconfig',
            name='product_table',
            field=models.CharField(choices=[('SIMPLE', 'SIMPLE'), ('GOODS', 'GOODS')], default='SIMPLE', max_length=20, verbose_name='成品表'),
        ),
        migrations.AlterField(
            model_name='indexidconfig',
            name='index_id',
            field=models.CharField(max_length=50, verbose_name='索引标识(INDEXID/TAG)'),
        ),
        migrations.AlterUniqueTogether(
            name='indexidconfig',
            unique_together={('product_table', 'index_id')},
        ),
    ]
