# Generated by Django 4.2.30 on 2026-07-08 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0009_alter_indexidconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, verbose_name='批次编号')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='批次描述')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '执行失败')], default='pending', max_length=20, verbose_name='状态')),
                ('total_cases', models.IntegerField(default=0, verbose_name='用例总数')),
                ('passed_count', models.IntegerField(default=0, verbose_name='通过数')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='跳过数')),
                ('current_progress', models.IntegerField(default=0, verbose_name='当前进度(%)')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='总执行时长(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '测试批次',
                'verbose_name_plural': '测试批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='automationtestresult',
            options={'ordering': ['-execution_date'], 'verbose_name': '自动化测试结果', 'verbose_name_plural': '自动化测试结果'},
        ),
        migrations.AlterField(
            model_name='automationtestresult',
            name='status',
            field=models.CharField(choices=[('passed', '通过'), ('failed', '失败'), ('skipped', '跳过'), ('running', '执行中')], max_length=20, verbose_name='执行状态'),
        ),
        migrations.AddField(
            model_name='automationtestresult',
            name='test_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='parameter.testbatch', verbose_name='关联测试批次'),
        ),
    ]
