# Generated by Django 4.2.30 on 2026-07-08 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0010_producttableconfig_testbatch_delete_indexidconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTableConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_table', models.CharField(choices=[('SIMPLE', 'SIMPLE'), ('GOODS', 'GOODS')], default='SIMPLE', max_length=20, verbose_name='成品表')),
                ('index_id', models.CharField(max_length=50, verbose_name='索引标识(INDEXID/TAG)')),
                ('business_name', models.CharField(max_length=200, verbose_name='业务名称')),
                ('business_description', models.TextField(blank=True, null=True, verbose_name='业务说明')),
                ('custom_column_names', models.JSONField(blank=True, null=True, verbose_name='自定义列名配置')),
                ('display_fields', models.JSONField(blank=True, null=True, verbose_name='显示字段配置')),
                ('validation_rules', models.JSONField(blank=True, null=True, verbose_name='校验规则配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '成品表复用配置',
                'verbose_name_plural': '成品表复用配置',
                'db_table': 'parameter_indexidconfig',
                'unique_together': {('product_table', 'index_id')},
            },
        ),
        migrations.DeleteModel(
            name='IndexIdConfig',
        ),
        migrations.AddField(
            model_name='testcase',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='是否确认'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认时间'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_test_cases', to='parameter.user', verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='parameter_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='parameter.parametertable', verbose_name='关联参数表'),
        ),
    ]
