# Generated by Django 4.2.30 on 2026-07-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0011_producttableconfig_delete_indexidconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='工号'),
        ),
    ]
